# \author  Neil Turton <neilt@amd.com>
#  \brief  Nanotube HLS output pass testing
#   \date  2020-08-07
#
###########################################################################
# Copyright (C) 2023, Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT
###########################################################################

Import('env')

src_filenames = [
    'bswap.cc',
    'casting.cc',
    'memcpy.cc',
    'mul_div.cc',
    'multi_stage.cc',
    'phi_node.cc',
    'pointers.cc',
    'shifts.cc',
    'simple.cc',
    'state.cc',
    'switch.cc',
    'variable_gep.cc',
]

for src_file in src_filenames:
    env.LlvmAsm(src_file)
