# \author  Neil Turton <neilt@amd.com>
#  \brief  Nanotube testing
#   \date  2020-08-02
#
###########################################################################
# Copyright (C) 2023, Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT
###########################################################################

Import('env')

llvm_config = env.get('LLVM_CONFIG')
if llvm_config == None:
    Return("")

env.add_subdir('unit_tests')
env.add_subdir('hls_out_tests')
env.add_subdir('kernel_tests')
env.add_subdir('harness')
env.add_subdir('support')
