# \author  Neil Turton <neilt@amd.com>
#  \brief  Nanotube test support
#   \date  2020-09-29
#
###########################################################################
# Copyright (C) 2023, Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT
###########################################################################
Import('env')

lib_sources = (
    'test.cpp',
)

env.Append(CPPPATH=['include'])
env.Library('test_support', lib_sources)
